### ISSUE TITLE
Should declare a license

### ISSUE THREAD

**Issue by joakime** [eirbjo/jetty-console#1]
Being that you are now open source, you should declare a license for your project.

This will include :
- some sort of file in the root of your GIT tree (like LICENSE.txt) - check your choice of license for what it recommends this file be called.
- inclusion of your chosen license in your pom.xml
- statement at the top of each source file with your license text (traditionally this is really only important in source files)
- optionally some maven-jar-plugin configuration to include the license in your archives (like in the META-INF directory)

**Comment by eirbjo** [comment]
JettyConsole was always licensed under APL-2, but yes, declaring it more prominently is a Good Thing.
