### ISSUE TITLE
can't find jetty-console-ajp-plugin dependency when including jetty-console-maven-plugin

### ISSUE THREAD

**Issue by mufumbo** [eirbjo/jetty-console#2]
I see multiple people having the same problem on stackoverflow. Would you shed a light how to solve this? 

[ERROR] Failed to execute goal org.simplericity.jettyconsole:jetty-console-maven-plugin:1.58:createconsole (default) on project craft-api: Unable to get dependency information for org.simplericity.jettyconsole:jetty-console-ajp-plugin:jar:1.58: Failed to retrieve POM for org.simplericity.jettyconsole:jetty-console-ajp-plugin:jar:1.58: Could not transfer artifact org.simplericity.jettyconsole:jetty-console-ajp-plugin:pom:1.58 from/to Java_Net_LEGACY (http://download.java.net/maven/1/): Cannot access http://download.java.net/maven/1/ with type legacy using the available connector factories: BasicRepositoryConnectorFactory
[ERROR] org.simplericity.jettyconsole:jetty-console-ajp-plugin:jar:1.58

**Comment by computerlove** [comment]
The AJP-plugin does not exist in newer versions. I believe the reason is that Jetty stopped supporting the protocol.
