### ISSUE TITLE
Start stop script

### ISSUE THREAD

**Issue by MRDcoder** [eirbjo/jetty-console#5]
Hi Team, 

I was looking into startstop.sh file generated by start stop plugin. I have some queries but there is no documentation for that script. Can you let me know how to use this script?

Also, while looking into script, i found 
NAME=%1$s
JAR="%2$s" 

Can you please let me know meaning of %1$s and "%2$s" ?

Thank you team:) @eirbjo

**Comment by eirbjo** [comment]
These are template variables used to produce the NAME and JAR values respectively. Look into the start-stop plugin to figure out how this is done.
